# Generated by Django 3.0.3 on 2020-05-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_event_grade_notes_result_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='criteria',
            field=models.CharField(default='default criteria', max_length=256),
        ),
    ]
